// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_Q, KC_W, KC_E, KC_R, KC_T,    KC_Y, KC_U,  KC_I,    KC_O,   KC_P,
        KC_A, KC_S, KC_D, KC_F, KC_G,    KC_H, KC_J,  KC_K,    KC_L,   KC_SCLN,
        KC_Z, KC_X, KC_C, KC_V, KC_B,    KC_N, KC_M,  KC_COMM, KC_DOT, KC_SLSH,
        KC_ESC, LSFT(KC_TAB), KC_LGUI , MO(2), KC_SPACE,    KC_ENT, MO(1), KC_LSFT, KC_RCTL, KC_BSPC
    ),

    [1] = LAYOUT(
        KC_1, KC_2, KC_3, KC_4, KC_5,    KC_6, KC_7,  KC_8,    KC_9,   KC_0,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,    KC_LEFT, KC_DOWN,  KC_UP,    KC_RIGHT,   XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,    XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX , XXXXXXX, XXXXXXX , XXXXXXX, XXXXXXX,    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX , XXXXXXX
    ),

    [2] = LAYOUT(
        KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC,    KC_CIRC, KC_AMPR,  KC_ASTR,    KC_LPRN,   KC_RPRN,
        KC_GRV,XXXXXXX,XXXXXXX,XXXXXXX, KC_QUOT,    KC_MINS, KC_EQL, KC_LBRC, KC_RBRC, KC_BSLS,
        KC_TILD,XXXXXXX,XXXXXXX,XXXXXXX, KC_DQUO,    KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE,
        XXXXXXX , XXXXXXX, XXXXXXX , XXXXXXX, XXXXXXX,    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX , XXXXXXX
    )

};
